<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqR2Hx1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqR2Hx1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqR2Hx1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqR2Hx1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqR2Hx1\App_KernelDevDebugContainer([
    'container.build_hash' => 'SqR2Hx1',
    'container.build_id' => 'ad75ea42',
    'container.build_time' => 1660586179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqR2Hx1');
